Update starsportshindi.yml workflow

diff --git a/.github/workflows/starsportshindi.yml b/.github/workflows/starsportshindi.yml
--- a/.github/workflows/starsportshindi.yml
+++ b/.github/workflows/starsportshindi.yml
@@ -6,27 +6,20 @@ on:
 jobs:
   starsportshindi:
     runs-on: ubuntu-latest
-    environment: Football
+    environment: Cricket
 
     steps:
       - name: Install ffmpeg 
         run: sudo apt update && sudo apt install ffmpeg -y
-      - name: Download Flussonic
-        run: sudo wget https://gist.githubusercontent.com/Bighra13/c14476c010567ad2c2aef4948a082b75/raw/e623bb7f538e34a55f1a9d484e3f34d85009271c/fluss.sh
-        
-        
-
-      - name: Install Flussonic 
-        run: sudo bash fluss.sh
 
       - name: Download remote bash file
-        run: wget ${{ secrets.FOOTBALL_PORTAL_URL }}/bash/starsportshindi.sh || echo "Primary URL download failed"
+        run: wget ${{ secrets.CRICKET_PORTAL_URL }}/bash/starsportshindi.sh || echo "Primary URL download failed"
         
       - name: Check if bash file exists and download from backup if not
         run: |
           if [ ! -f starsportshindi.sh ]; then
             echo "Primary URL file not found, downloading from backup URL"
-            wget ${{ secrets.FOOTBALL_BACKUP_BASH_URL }}/starsportshindi.sh
+            wget ${{ secrets.CRICKET_BACKUP_BASH_URL }}/starsportshindi.sh
           else
             echo "Bash file downloaded successfully"
           fi
